name: Test
on:
  - push
jobs:
  build:
    name: Test
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - name: Create Release
        if: |
          startsWith(github.ref, 'refs/tags/')
        run: |
          gh release create ${GITHUB_REF_NAME} \
          --notes-file README.md \
          README.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
