name: Test
on:
  pull_request:
  push:
    tags:
      - v1.*

jobs:
  define-matrix:
    runs-on: ubuntu-latest
    env:
      ALL_COMPONENTS: >
        [
        "debian-azureblob",
        "debian-cloudwatch",
        "debian-elasticsearch7",
        "debian-elasticsearch8",
        "debian-forward",
        "debian-gcs",
        "debian-graylog",
        "debian-kafka2",
        "debian-kafka",
        "debian-kinesis",
        "debian-logentries",
        "debian-loggly",
        "debian-logzio",
        "debian-opensearch",
        "debian-papertrail",
        "debian-s3",
        "debian-syslog"
        ]
    outputs:
      components: >
        ${{ steps.arrange-components.outputs.for_all == 'true' && env.ALL_COMPONENTS
        || format('["{0}"]', steps.arrange-components.outputs.component) }}
    steps:
      - id: arrange-components
        run: |
          echo "for_all=true" >> "$GITHUB_OUTPUT"
          echo "${{ github.ref_type }}"
          if [ "${{ github.ref_type }}" != tag ]; then
            exit 0
          fi
          for component in ${{ join(fromJSON(env.ALL_COMPONENTS), ' ') }}; do
            if [[ ${{ github.ref_name }} == *"$component"* ]]; then
              echo "for_all=false" >> "$GITHUB_OUTPUT"
              echo "component=$component" >> "$GITHUB_OUTPUT"
              break
            fi
          done
  build:
    needs: define-matrix
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        component: ${{ fromJSON(needs.define-matrix.outputs.components) }}
    steps:
      - name: Build
        run: |
          echo ${{ matrix.component }}
          echo ${{ startsWith(github.ref, 'refs/tags/v1.') }}
  push:
    if: ${{ startsWith(github.ref, 'refs/tags/v1.') }}
    needs: [define-matrix, build]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        component: ${{ fromJSON(needs.define-matrix.outputs.components) }}
    steps:
      - name: Push
        run: |
          echo ${{ matrix.component }}
          echo PUSH!!
