name: Test
on:
  - push
jobs:
  define-matrix:
    runs-on: ubuntu-latest
    outputs:
      contexts: ${{ steps.set-contexts.outputs.contexts }}
    steps:
      - id: set-contexts
        run: |
          contexts=$(echo '[
            "debian-azureblob",
            "debian-cloudwatch",
            "debian-elasticsearch7",
            "debian-elasticsearch8",
            "debian-forward",
            "debian-gcs",
            "debian-graylog",
            "debian-kafka",
            "debian-kafka2",
            "debian-kinesis",
            "debian-logentries",
            "debian-loggly",
            "debian-logzio",
            "debian-opensearch",
            "debian-papertrail",
            "debian-s3",
            "debian-syslog"
            ]' | jq -c)
          echo "contexts=$contexts" >> "$GITHUB_OUTPUT"
  amd64:
    needs: define-matrix
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        context: ${{ fromJSON(needs.define-matrix.outputs.contexts) }}
    steps:
      - uses: actions/checkout@v3
      - name: Test
        run: |
          echo ${{ matrix.context }}
