name: Test2
on:
  pull_request:
  push:
    tags:
      - v1.*

jobs:
  define-matrix:
    runs-on: ubuntu-latest
    env:
      ALL_COMPONENTS: >
        [
        "alpine",
        "arm64",
        "armhf",
        "amd64",
        ]
    outputs:
      components: >
        ${{ steps.arrange-components.outputs.for_all == 'true' && env.ALL_COMPONENTS
        || format('["{0}"]', steps.arrange-components.outputs.component) }}
    steps:
      - id: arrange-components
        run: |
          echo "for_all=true" >> "$GITHUB_OUTPUT"
          for component in ${{ join(fromJSON(env.ALL_COMPONENTS), ' ') }}; do
            if [[ ${{ github.ref_name }} == *"$component"* ]]; then
              echo "for_all=false" >> "$GITHUB_OUTPUT"
              echo "component=$component" >> "$GITHUB_OUTPUT"
              break
            fi
          done
  build:
    needs: define-matrix
    strategy:
      fail-fast: false
      matrix:
        component: ${{ fromJSON(needs.define-matrix.outputs.components) }}
        include:
          - runs-on: ubuntu-latest
          - runs-on: ubuntu-24.04-arm
            component: arm64
    runs-on: matrix.runs-on
    steps:
      - name: Build
        run: |
          echo ${{ matrix.component }}
          echo ${{ startsWith(github.ref, 'refs/tags/v1.') }}
  push:
    if: ${{ startsWith(github.ref, 'refs/tags/v1.') }}
    needs: [define-matrix, build]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        component: ${{ fromJSON(needs.define-matrix.outputs.components) }}
    steps:
      - name: Push
        run: |
          echo ${{ matrix.component }}
          echo PUSH!!
